### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by jlhsr** [alvin0319/RCEncryption#1]
![KBLGIUPLZ2GC5}8OC( 0OCA](https://user-images.githubusercontent.com/22098995/189410719-0a54bda8-1931-4025-aee9-1cd01c0955d1.png)
Logo chat bar changes and item ICONS are all invalid

The latest plug-in has been downloaded and encrypted using the website you provided and the corresponding key has been configured for the plug-in

**Comment by alvin0319** [comment]
How did you set up your config? Can you paste it here? (Please remove the content key)

**Comment by alvin0319** [comment]
Closing this issue due to no reply.
