### ISSUE TITLE
 https://encryptmypack.com Failed to upload file

### ISSUE THREAD

**Issue by kitkung2411** [alvin0319/RCEncryption#2]
https://encryptmypack.com Failed to upload file

**Comment by stevei5mc** [comment]
![Screenshot_20221121_100632_mark via](https://user-images.githubusercontent.com/82391055/202945437-65d0fd75-4f38-4416-8e26-6146b7c08bc0.png)

**Comment by stevei5mc** [comment]
use encrypt
https://github.com/valaphee/mcrputil

**Comment by alvin0319** [comment]
This is not a support hotline for encryptmypack.
